// Add invisible watermarks to generated content for tracking
import { addCopyrightNotice } from './copyright';

export function watermarkContent(content: string, userId: string): string {
  const timestamp = Date.now();
  const watermark = `<!-- Generated by Studio ${userId} at ${timestamp} -->`;

  // Add both watermark and copyright
  const withWatermark = content + '\n' + watermark;
  return addCopyrightNotice(withWatermark, {
    author: userId,
    createdAt: new Date(timestamp),
    id: timestamp
  });
}

export function watermarkJSON(data: any, userId: string): any {
  const timestamp = Date.now();
  return {
    ...data,
    _metadata: {
      generatedBy: userId,
      timestamp,
      source: 'Unified-3D-Production-Studio'
    }
  };
}

// Example usage:
// const markedContent = watermarkContent(generatedScript, req.user.id);
// const markedData = watermarkJSON(castingProfile, req.user.id);
