// Add legal metadata to all API responses

const LEGAL_INFO = {
  company: {
    legal_name: "The AI Content Foundry LLC",
  },
  product: {
    name: "Finesse Jones Production Studio",
    version: "1.0.0",
  },
  copyright: {
    owner: "The AI Content Foundry LLC",
    notice: "© 2025 The AI Content Foundry LLC. All rights reserved.",
  },
};

export interface ApiResponse<T = any> {
  data: T;
  meta: ApiMetadata;
  _copyright?: CopyrightMetadata;
}

export interface ApiMetadata {
  timestamp: string;
  requestId?: string;
  version: string;
}

export interface CopyrightMetadata {
  owner: string;
  notice: string;
  product: string;
  version: string;
  generated_at: string;
}

/**
 * Wrap API response with legal metadata
 */
export function withLegalMetadata<T>(data: T, requestId?: string): ApiResponse<T> {
  return {
    data,
    meta: {
      timestamp: new Date().toISOString(),
      requestId,
      version: LEGAL_INFO.product.version,
    },
    _copyright: {
      owner: LEGAL_INFO.copyright.owner,
      notice: LEGAL_INFO.copyright.notice,
      product: LEGAL_INFO.product.name,
      version: LEGAL_INFO.product.version,
      generated_at: new Date().toISOString(),
    },
  };
}

/**
 * Add copyright to exported content
 */
export function addExportMetadata(
  content: string,
  metadata: {
    type: string;
    author: string;
    projectId: string;
  }
): string {
  const header = `
Generated by ${LEGAL_INFO.product.name}
${LEGAL_INFO.copyright.notice}

Type: ${metadata.type}
Author: ${metadata.author}
Project: ${metadata.projectId}
Created: ${new Date().toISOString()}

---

`;

  const footer = `

---

${LEGAL_INFO.copyright.notice}
Created using ${LEGAL_INFO.product.name}
All rights reserved. Unauthorized reproduction or distribution prohibited.
`;

  return header + content + footer;
}
