// Code generated by the Encore 1.48.8 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly ai: ai.ServiceClient
    public readonly studio: studio.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.ai = new ai.ServiceClient(base)
        this.studio = new studio.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    analyzeSelfTape as api_ai_casting_director_analyzeSelfTape,
    generateAuditionSides as api_ai_casting_director_generateAuditionSides,
    generateCastingProfile as api_ai_casting_director_generateCastingProfile
} from "~backend/ai/casting_director";
import {
    generatePressKit as api_ai_distribution_desk_generatePressKit,
    generateReleaseStrategy as api_ai_distribution_desk_generateReleaseStrategy,
    generateScreener as api_ai_distribution_desk_generateScreener
} from "~backend/ai/distribution_desk";
import {
    applyAudioMix as api_ai_editing_suite_applyAudioMix,
    applyColorGrade as api_ai_editing_suite_applyColorGrade,
    applyEdit as api_ai_editing_suite_applyEdit,
    applyVFX as api_ai_editing_suite_applyVFX,
    exportEdit as api_ai_editing_suite_exportEdit,
    startEditingSession as api_ai_editing_suite_startEditingSession
} from "~backend/ai/editing_suite";
import {
    generateForm as api_ai_forms_generator_generateForm,
    generateFormPackage as api_ai_forms_generator_generateFormPackage
} from "~backend/ai/forms_generator";
import {
    exportPlatformPackage as api_ai_platform_optimizer_exportPlatformPackage,
    optimizeForPlatform as api_ai_platform_optimizer_optimizeForPlatform
} from "~backend/ai/platform_optimizer";
import {
    generateEditNotes as api_ai_post_production_generateEditNotes,
    generateVFXHandoff as api_ai_post_production_generateVFXHandoff,
    generateVersionTracking as api_ai_post_production_generateVersionTracking
} from "~backend/ai/post_production";
import {
    generateCallSheet as api_ai_production_coordinator_generateCallSheet,
    generateProductionCalendar as api_ai_production_coordinator_generateProductionCalendar,
    generateShotList as api_ai_production_coordinator_generateShotList
} from "~backend/ai/production_coordinator";
import {
    convertNovel as api_ai_screenwriting_assistant_convertNovel,
    createWritingRoomSession as api_ai_screenwriting_assistant_createWritingRoomSession,
    editScript as api_ai_screenwriting_assistant_editScript,
    generateScript as api_ai_screenwriting_assistant_generateScript
} from "~backend/ai/screenwriting_assistant";
import {
    checkContinuity as api_ai_script_supervisor_checkContinuity,
    generateScriptBreakdown as api_ai_script_supervisor_generateScriptBreakdown,
    generateShootingScript as api_ai_script_supervisor_generateShootingScript
} from "~backend/ai/script_supervisor";
import {
    generatePrevisualization as api_ai_virtual_camera_generatePrevisualization,
    generateStoryboard as api_ai_virtual_camera_generateStoryboard,
    simulateCameraShot as api_ai_virtual_camera_simulateCameraShot
} from "~backend/ai/virtual_camera";

export namespace ai {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.analyzeSelfTape = this.analyzeSelfTape.bind(this)
            this.applyAudioMix = this.applyAudioMix.bind(this)
            this.applyColorGrade = this.applyColorGrade.bind(this)
            this.applyEdit = this.applyEdit.bind(this)
            this.applyVFX = this.applyVFX.bind(this)
            this.checkContinuity = this.checkContinuity.bind(this)
            this.convertNovel = this.convertNovel.bind(this)
            this.createWritingRoomSession = this.createWritingRoomSession.bind(this)
            this.editScript = this.editScript.bind(this)
            this.exportEdit = this.exportEdit.bind(this)
            this.exportPlatformPackage = this.exportPlatformPackage.bind(this)
            this.generateAuditionSides = this.generateAuditionSides.bind(this)
            this.generateCallSheet = this.generateCallSheet.bind(this)
            this.generateCastingProfile = this.generateCastingProfile.bind(this)
            this.generateEditNotes = this.generateEditNotes.bind(this)
            this.generateForm = this.generateForm.bind(this)
            this.generateFormPackage = this.generateFormPackage.bind(this)
            this.generatePressKit = this.generatePressKit.bind(this)
            this.generatePrevisualization = this.generatePrevisualization.bind(this)
            this.generateProductionCalendar = this.generateProductionCalendar.bind(this)
            this.generateReleaseStrategy = this.generateReleaseStrategy.bind(this)
            this.generateScreener = this.generateScreener.bind(this)
            this.generateScript = this.generateScript.bind(this)
            this.generateScriptBreakdown = this.generateScriptBreakdown.bind(this)
            this.generateShootingScript = this.generateShootingScript.bind(this)
            this.generateShotList = this.generateShotList.bind(this)
            this.generateStoryboard = this.generateStoryboard.bind(this)
            this.generateVFXHandoff = this.generateVFXHandoff.bind(this)
            this.generateVersionTracking = this.generateVersionTracking.bind(this)
            this.optimizeForPlatform = this.optimizeForPlatform.bind(this)
            this.simulateCameraShot = this.simulateCameraShot.bind(this)
            this.startEditingSession = this.startEditingSession.bind(this)
        }

        /**
         * Analyzes self-tape submissions and provides casting recommendations.
         */
        public async analyzeSelfTape(params: RequestType<typeof api_ai_casting_director_analyzeSelfTape>): Promise<ResponseType<typeof api_ai_casting_director_analyzeSelfTape>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/casting/analyze-tape`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_casting_director_analyzeSelfTape>
        }

        /**
         * Applies audio mixing with AI enhancement.
         */
        public async applyAudioMix(params: RequestType<typeof api_ai_editing_suite_applyAudioMix>): Promise<ResponseType<typeof api_ai_editing_suite_applyAudioMix>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/editing/audio-mix`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_editing_suite_applyAudioMix>
        }

        /**
         * Applies AI-enhanced color grading to footage.
         */
        public async applyColorGrade(params: RequestType<typeof api_ai_editing_suite_applyColorGrade>): Promise<ResponseType<typeof api_ai_editing_suite_applyColorGrade>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/editing/color-grade`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_editing_suite_applyColorGrade>
        }

        /**
         * Applies an edit operation to the timeline.
         */
        public async applyEdit(params: RequestType<typeof api_ai_editing_suite_applyEdit>): Promise<ResponseType<typeof api_ai_editing_suite_applyEdit>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/editing/apply`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_editing_suite_applyEdit>
        }

        /**
         * Applies VFX processing to shots.
         */
        public async applyVFX(params: RequestType<typeof api_ai_editing_suite_applyVFX>): Promise<ResponseType<typeof api_ai_editing_suite_applyVFX>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/editing/vfx`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_editing_suite_applyVFX>
        }

        /**
         * Performs continuity checks and tracks script revisions.
         */
        public async checkContinuity(params: RequestType<typeof api_ai_script_supervisor_checkContinuity>): Promise<ResponseType<typeof api_ai_script_supervisor_checkContinuity>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/script-supervisor/continuity`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_script_supervisor_checkContinuity>
        }

        /**
         * Converts a novel into a film treatment and screenplay while preserving style.
         */
        public async convertNovel(params: RequestType<typeof api_ai_screenwriting_assistant_convertNovel>): Promise<ResponseType<typeof api_ai_screenwriting_assistant_convertNovel>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/screenwriting/convert-novel`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_screenwriting_assistant_convertNovel>
        }

        /**
         * Creates a collaborative writing room session with multiple perspectives.
         */
        public async createWritingRoomSession(params: RequestType<typeof api_ai_screenwriting_assistant_createWritingRoomSession>): Promise<ResponseType<typeof api_ai_screenwriting_assistant_createWritingRoomSession>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/screenwriting/writing-room`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_screenwriting_assistant_createWritingRoomSession>
        }

        /**
         * Edits and refines existing scripts with specific focus areas.
         */
        public async editScript(params: RequestType<typeof api_ai_screenwriting_assistant_editScript>): Promise<ResponseType<typeof api_ai_screenwriting_assistant_editScript>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/screenwriting/edit`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_screenwriting_assistant_editScript>
        }

        /**
         * Exports the final edited project.
         */
        public async exportEdit(params: RequestType<typeof api_ai_editing_suite_exportEdit>): Promise<ResponseType<typeof api_ai_editing_suite_exportEdit>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/editing/export`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_editing_suite_exportEdit>
        }

        /**
         * Exports optimized package for platform delivery.
         */
        public async exportPlatformPackage(params: RequestType<typeof api_ai_platform_optimizer_exportPlatformPackage>): Promise<ResponseType<typeof api_ai_platform_optimizer_exportPlatformPackage>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/platform/export`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_platform_optimizer_exportPlatformPackage>
        }

        /**
         * Creates audition sides from script content for specific characters.
         */
        public async generateAuditionSides(params: RequestType<typeof api_ai_casting_director_generateAuditionSides>): Promise<ResponseType<typeof api_ai_casting_director_generateAuditionSides>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/casting/audition-sides`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_casting_director_generateAuditionSides>
        }

        /**
         * Creates detailed call sheets with all production information.
         */
        public async generateCallSheet(params: RequestType<typeof api_ai_production_coordinator_generateCallSheet>): Promise<ResponseType<typeof api_ai_production_coordinator_generateCallSheet>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/production/call-sheet`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_production_coordinator_generateCallSheet>
        }

        /**
         * Generates comprehensive casting profiles and sheets for characters.
         */
        public async generateCastingProfile(params: RequestType<typeof api_ai_casting_director_generateCastingProfile>): Promise<ResponseType<typeof api_ai_casting_director_generateCastingProfile>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/casting/profile`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_casting_director_generateCastingProfile>
        }

        /**
         * Analyzes rough cuts and provides intelligent editing suggestions.
         */
        public async generateEditNotes(params: RequestType<typeof api_ai_post_production_generateEditNotes>): Promise<ResponseType<typeof api_ai_post_production_generateEditNotes>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/post-production/edit-notes`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_post_production_generateEditNotes>
        }

        /**
         * Generates any standard film industry form with customization options.
         */
        public async generateForm(params: RequestType<typeof api_ai_forms_generator_generateForm>): Promise<ResponseType<typeof api_ai_forms_generator_generateForm>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/forms/generate`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_forms_generator_generateForm>
        }

        /**
         * Creates complete form packages for specific production phases.
         */
        public async generateFormPackage(params: RequestType<typeof api_ai_forms_generator_generateFormPackage>): Promise<ResponseType<typeof api_ai_forms_generator_generateFormPackage>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/forms/package`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_forms_generator_generateFormPackage>
        }

        /**
         * Generates comprehensive press kits with marketing materials.
         */
        public async generatePressKit(params: RequestType<typeof api_ai_distribution_desk_generatePressKit>): Promise<ResponseType<typeof api_ai_distribution_desk_generatePressKit>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/distribution/press-kit`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_distribution_desk_generatePressKit>
        }

        /**
         * Creates 3D previsualization with character blocking and camera positioning.
         */
        public async generatePrevisualization(params: RequestType<typeof api_ai_virtual_camera_generatePrevisualization>): Promise<ResponseType<typeof api_ai_virtual_camera_generatePrevisualization>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/virtual-camera/previs`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_virtual_camera_generatePrevisualization>
        }

        /**
         * Generates comprehensive production calendar with automated scheduling.
         */
        public async generateProductionCalendar(params: RequestType<typeof api_ai_production_coordinator_generateProductionCalendar>): Promise<ResponseType<typeof api_ai_production_coordinator_generateProductionCalendar>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/production/calendar`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_production_coordinator_generateProductionCalendar>
        }

        /**
         * Develops comprehensive release strategies for different platforms.
         */
        public async generateReleaseStrategy(params: RequestType<typeof api_ai_distribution_desk_generateReleaseStrategy>): Promise<ResponseType<typeof api_ai_distribution_desk_generateReleaseStrategy>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/distribution/release-strategy`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_distribution_desk_generateReleaseStrategy>
        }

        /**
         * Creates secure screener packages for different recipient types.
         */
        public async generateScreener(params: RequestType<typeof api_ai_distribution_desk_generateScreener>): Promise<ResponseType<typeof api_ai_distribution_desk_generateScreener>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/distribution/screener`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_distribution_desk_generateScreener>
        }

        /**
         * Generates a complete screenplay from a prompt using specified structure.
         */
        public async generateScript(params: RequestType<typeof api_ai_screenwriting_assistant_generateScript>): Promise<ResponseType<typeof api_ai_screenwriting_assistant_generateScript>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/screenwriting/generate`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_screenwriting_assistant_generateScript>
        }

        /**
         * Creates comprehensive script breakdown sheets with color coding.
         */
        public async generateScriptBreakdown(params: RequestType<typeof api_ai_script_supervisor_generateScriptBreakdown>): Promise<ResponseType<typeof api_ai_script_supervisor_generateScriptBreakdown>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/script-supervisor/breakdown`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_script_supervisor_generateScriptBreakdown>
        }

        /**
         * Generates a professional shooting script with scene numbers and breakdown.
         */
        public async generateShootingScript(params: RequestType<typeof api_ai_script_supervisor_generateShootingScript>): Promise<ResponseType<typeof api_ai_script_supervisor_generateShootingScript>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/script-supervisor/shooting-script`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_script_supervisor_generateShootingScript>
        }

        /**
         * Generates detailed shot lists with camera and equipment specifications.
         */
        public async generateShotList(params: RequestType<typeof api_ai_production_coordinator_generateShotList>): Promise<ResponseType<typeof api_ai_production_coordinator_generateShotList>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/production/shot-list`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_production_coordinator_generateShotList>
        }

        /**
         * Generates dynamic storyboards from script content with visual style guidance.
         */
        public async generateStoryboard(params: RequestType<typeof api_ai_virtual_camera_generateStoryboard>): Promise<ResponseType<typeof api_ai_virtual_camera_generateStoryboard>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/virtual-camera/storyboard`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_virtual_camera_generateStoryboard>
        }

        /**
         * Creates comprehensive VFX handoff packages with technical specifications.
         */
        public async generateVFXHandoff(params: RequestType<typeof api_ai_post_production_generateVFXHandoff>): Promise<ResponseType<typeof api_ai_post_production_generateVFXHandoff>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/post-production/vfx-handoff`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_post_production_generateVFXHandoff>
        }

        /**
         * Manages version control and approval workflows for post-production.
         */
        public async generateVersionTracking(params: RequestType<typeof api_ai_post_production_generateVersionTracking>): Promise<ResponseType<typeof api_ai_post_production_generateVersionTracking>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/post-production/version-tracking`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_post_production_generateVersionTracking>
        }

        /**
         * Optimizes content for specific platforms with detailed specifications.
         */
        public async optimizeForPlatform(params: RequestType<typeof api_ai_platform_optimizer_optimizeForPlatform>): Promise<ResponseType<typeof api_ai_platform_optimizer_optimizeForPlatform>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/platform/optimize`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_platform_optimizer_optimizeForPlatform>
        }

        /**
         * Simulates camera shots with technical specifications and movement profiles.
         */
        public async simulateCameraShot(params: RequestType<typeof api_ai_virtual_camera_simulateCameraShot>): Promise<ResponseType<typeof api_ai_virtual_camera_simulateCameraShot>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/virtual-camera/simulate`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_virtual_camera_simulateCameraShot>
        }

        /**
         * Starts a new editing session with AI-enhanced capabilities.
         */
        public async startEditingSession(params: RequestType<typeof api_ai_editing_suite_startEditingSession>): Promise<ResponseType<typeof api_ai_editing_suite_startEditingSession>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/editing/session/start`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_editing_suite_startEditingSession>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createProject as api_studio_create_project_createProject } from "~backend/studio/create_project";
import { getProject as api_studio_get_project_getProject } from "~backend/studio/get_project";
import { listProjects as api_studio_list_projects_listProjects } from "~backend/studio/list_projects";
import {
    createProjectFile as api_studio_project_files_createProjectFile,
    getProjectFiles as api_studio_project_files_getProjectFiles,
    updateProjectFile as api_studio_project_files_updateProjectFile
} from "~backend/studio/project_files";
import { updateProjectStatus as api_studio_update_project_status_updateProjectStatus } from "~backend/studio/update_project_status";

export namespace studio {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createProject = this.createProject.bind(this)
            this.createProjectFile = this.createProjectFile.bind(this)
            this.getProject = this.getProject.bind(this)
            this.getProjectFiles = this.getProjectFiles.bind(this)
            this.listProjects = this.listProjects.bind(this)
            this.updateProjectFile = this.updateProjectFile.bind(this)
            this.updateProjectStatus = this.updateProjectStatus.bind(this)
        }

        /**
         * Creates a new film project with automated setup.
         */
        public async createProject(params: RequestType<typeof api_studio_create_project_createProject>): Promise<ResponseType<typeof api_studio_create_project_createProject>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_studio_create_project_createProject>
        }

        /**
         * Creates a new file in the project file cabinet.
         */
        public async createProjectFile(params: RequestType<typeof api_studio_project_files_createProjectFile>): Promise<ResponseType<typeof api_studio_project_files_createProjectFile>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                content:     params.content,
                "file_name": params["file_name"],
                "file_type": params["file_type"],
                metadata:    params.metadata,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.project_id)}/files`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_studio_project_files_createProjectFile>
        }

        /**
         * Retrieves a specific project with all associated data.
         */
        public async getProject(params: { id: number }): Promise<ResponseType<typeof api_studio_get_project_getProject>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_studio_get_project_getProject>
        }

        /**
         * Retrieves all files for a project from the file cabinet.
         */
        public async getProjectFiles(params: RequestType<typeof api_studio_project_files_getProjectFiles>): Promise<ResponseType<typeof api_studio_project_files_getProjectFiles>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "file_type": params["file_type"],
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.project_id)}/files`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_studio_project_files_getProjectFiles>
        }

        /**
         * Retrieves all film projects, ordered by creation date (latest first).
         */
        public async listProjects(): Promise<ResponseType<typeof api_studio_list_projects_listProjects>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_studio_list_projects_listProjects>
        }

        /**
         * Updates an existing file in the project file cabinet.
         */
        public async updateProjectFile(params: RequestType<typeof api_studio_project_files_updateProjectFile>): Promise<ResponseType<typeof api_studio_project_files_updateProjectFile>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                content:  params.content,
                metadata: params.metadata,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/files/${encodeURIComponent(params.file_id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_studio_project_files_updateProjectFile>
        }

        /**
         * Updates a project's production status and triggers automated workflow changes.
         */
        public async updateProjectStatus(params: RequestType<typeof api_studio_update_project_status_updateProjectStatus>): Promise<ResponseType<typeof api_studio_update_project_status_updateProjectStatus>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                status: params.status,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.id)}/status`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_studio_update_project_status_updateProjectStatus>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.48.8)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

// Get the API base URL from environment or use production default
const getAPIURL = () => {
  if (import.meta.env.VITE_API_URL) return import.meta.env.VITE_API_URL;
    if (typeof window !== 'undefined') return window.location.origin;
  return 'http://localhost:4000';
};

export default new Client(getAPIURL(), { requestInit: { credentials: "include" } });
